package aula.excecao;
  
public class CPF_Expetion extends Exception
{  
	private String msg;  
	public CPF_Expetion()
	{  
		super("CPF Invalido");  
		this.msg = "CPF Invalido";  
	}  
	public String getMessage(){  
		return msg;  
	}
}

public class Principal_novaExcecao 
{	
	public static void testar_cpf(String codigo) throws CPF_Expetion
	{
		if(!validacaoCPF._verificaCPF(codigo))
			throw new CPF_Expetion();
	}

	public static void main(String[] args) 
	{
		try {
			testar_cpf("000.000.000-00");
			System.out.println("cpf correto");
		} 
		catch (CPF_Expetion e) 
		{
			System.out.println(e.getMessage());
		}
	}
}